sudo: false
language: python
python:
   -    "2.7"
   -    "3.6"

env:
    KATPACKAGE=${PWD##*/}
    test_flags="--with-xunit --with-xcoverage --cover-package=${KATPACKAGE} --cover-inclusive"
 
install:
  -     pip install tox-travis

script:
  -    tox
